/**
 * Linked Events information API
 * Linked Events provides categorized data on events and places using JSON-LD format.  Events can be searched by date and location. Location can be exact address or larger area such as neighbourhood or borough  JSON-LD format is streamlined using include mechanism. API users can request that certain fields are included directly into the result, instead of being hyperlinks to objects.  Several fields are multilingual. These are implemented as object with each language variant as property. In this specification each multilingual field has (fi,sv,en) property triplet as example.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The PlacePosition model module.
* @module model/PlacePosition
* @version 0.0.1
*/
export default class PlacePosition {
    /**
    * Constructs a new <code>PlacePosition</code>.
    * geographic position of the place specified using subset of GeoJSON
    * @alias module:model/PlacePosition
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>PlacePosition</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/PlacePosition} obj Optional instance to populate.
    * @return {module:model/PlacePosition} The populated <code>PlacePosition</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PlacePosition();

            
            
            

            if (data.hasOwnProperty('coordinates')) {
                obj['coordinates'] = ApiClient.convertToType(data['coordinates'], ['Number']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * coordinates in format specified by type property
    * @member {Array.<Number>} coordinates
    */
    coordinates = undefined;
    /**
    * interpretation of the coordinates property. Only point is supported in this version
    * @member {module:model/PlacePosition.TypeEnum} type
    */
    type = undefined;






    /**
    * Allowed values for the <code>type</code> property.
    * @enum {String}
    * @readonly
    */
    static TypeEnum = {
    
        /**
         * value: "Point"
         * @const
         */
        "Point": "Point"    
    };



}


