/**
 * Linked Events information API
 * Linked Events provides categorized data on events and places using JSON-LD format.  Events can be searched by date and location. Location can be exact address or larger area such as neighbourhood or borough  JSON-LD format is streamlined using include mechanism. API users can request that certain fields are included directly into the result, instead of being hyperlinks to objects.  Several fields are multilingual. These are implemented as object with each language variant as property. In this specification each multilingual field has (fi,sv,en) property triplet as example.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LinkedeventsClient);
  }
}(this, function(expect, LinkedeventsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LinkedeventsClient.Place();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Place', function() {
    it('should create an instance of Place', function() {
      // uncomment below and update the code to test Place
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be.a(LinkedeventsClient.Place);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property customData (base name: "custom_data")', function() {
      // uncomment below and update the code to test the property customData
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property images (base name: "images")', function() {
      // uncomment below and update the code to test the property images
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property originId (base name: "origin_id")', function() {
      // uncomment below and update the code to test the property originId
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property createdTime (base name: "created_time")', function() {
      // uncomment below and update the code to test the property createdTime
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property lastModifiedTime (base name: "last_modified_time")', function() {
      // uncomment below and update the code to test the property lastModifiedTime
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property infoUrl (base name: "info_url")', function() {
      // uncomment below and update the code to test the property infoUrl
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property position (base name: "position")', function() {
      // uncomment below and update the code to test the property position
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property telephone (base name: "telephone")', function() {
      // uncomment below and update the code to test the property telephone
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property contactType (base name: "contact_type")', function() {
      // uncomment below and update the code to test the property contactType
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property streetAddress (base name: "street_address")', function() {
      // uncomment below and update the code to test the property streetAddress
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property addressLocality (base name: "address_locality")', function() {
      // uncomment below and update the code to test the property addressLocality
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property addressRegion (base name: "address_region")', function() {
      // uncomment below and update the code to test the property addressRegion
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property postalCode (base name: "postal_code")', function() {
      // uncomment below and update the code to test the property postalCode
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property postOfficeBoxNum (base name: "post_office_box_num")', function() {
      // uncomment below and update the code to test the property postOfficeBoxNum
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property addressCountry (base name: "address_country")', function() {
      // uncomment below and update the code to test the property addressCountry
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property deleted (base name: "deleted")', function() {
      // uncomment below and update the code to test the property deleted
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property dataSource (base name: "data_source")', function() {
      // uncomment below and update the code to test the property dataSource
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

    it('should have the property publisher (base name: "publisher")', function() {
      // uncomment below and update the code to test the property publisher
      //var instane = new LinkedeventsClient.Place();
      //expect(instance).to.be();
    });

  });

}));
