/**
 * Linked Events information API
 * Linked Events provides categorized data on events and places using JSON-LD format.  Events can be searched by date and location. Location can be exact address or larger area such as neighbourhood or borough  JSON-LD format is streamlined using include mechanism. API users can request that certain fields are included directly into the result, instead of being hyperlinks to objects.  Several fields are multilingual. These are implemented as object with each language variant as property. In this specification each multilingual field has (fi,sv,en) property triplet as example.
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LinkedeventsClient);
  }
}(this, function(expect, LinkedeventsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LinkedeventsClient.FilterApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FilterApi', function() {
    describe('keywordCreate', function() {
      it('should call keywordCreate successfully', function(done) {
        //uncomment below and update the code to test keywordCreate
        //instance.keywordCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('keywordDelete', function() {
      it('should call keywordDelete successfully', function(done) {
        //uncomment below and update the code to test keywordDelete
        //instance.keywordDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('keywordList', function() {
      it('should call keywordList successfully', function(done) {
        //uncomment below and update the code to test keywordList
        //instance.keywordList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('keywordRetrieve', function() {
      it('should call keywordRetrieve successfully', function(done) {
        //uncomment below and update the code to test keywordRetrieve
        //instance.keywordRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('keywordSetList', function() {
      it('should call keywordSetList successfully', function(done) {
        //uncomment below and update the code to test keywordSetList
        //instance.keywordSetList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('keywordSetRetrieve', function() {
      it('should call keywordSetRetrieve successfully', function(done) {
        //uncomment below and update the code to test keywordSetRetrieve
        //instance.keywordSetRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('keywordUpdate', function() {
      it('should call keywordUpdate successfully', function(done) {
        //uncomment below and update the code to test keywordUpdate
        //instance.keywordUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('placeCreate', function() {
      it('should call placeCreate successfully', function(done) {
        //uncomment below and update the code to test placeCreate
        //instance.placeCreate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('placeDelete', function() {
      it('should call placeDelete successfully', function(done) {
        //uncomment below and update the code to test placeDelete
        //instance.placeDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('placeList', function() {
      it('should call placeList successfully', function(done) {
        //uncomment below and update the code to test placeList
        //instance.placeList(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('placeRetrieve', function() {
      it('should call placeRetrieve successfully', function(done) {
        //uncomment below and update the code to test placeRetrieve
        //instance.placeRetrieve(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('placeUpdate', function() {
      it('should call placeUpdate successfully', function(done) {
        //uncomment below and update the code to test placeUpdate
        //instance.placeUpdate(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
